[package]
name = "moonbeam-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.10"
syn = { version = "1.0.81", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.32"

[dev-dependencies]
lunatic = "0.7.0"
serde = "1.0.130"